name: eyeapp3d
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.1
  equatable: ^2.0.7
  http: ^1.3.0
  
  # ui
  video_player: ^2.9.5
  webview_flutter: ^4.11.0
  carousel_slider: ^5.0.0

  # file
  file_picker: ^10.1.2
  file_utils: ^1.0.1
  path_provider: ^2.1.5
  
  # local dat
  shared_preferences: ^2.5.3
  camera: ^0.11.1
  gal: ^2.3.1
  model_viewer_plus: ^1.9.3
  permission_handler: ^12.0.0+1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  share_plus: ^11.0.0
  just_audio: ^0.10.3
  cupertino_icons: ^1.0.8
  # flutter_gemma: ^0.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/image/
    - .env
  